---
- name: Include apt_systems.yml
  include: apt_systems.yml
  when: ansible_pkg_mgr == "apt"

# Yum systems support is not implemented yet.
- name: Include yum_systems.yml
  include: yum_systems.yml
  when: ansible_pkg_mgr == "yum"

# Set up the different users that teuthology uses
- name: Include setup_users.yml
  include: setup_users.yml

- name: Ship /etc/teuthology.yaml
  template:
    src: teuthology.yaml
    dest: /etc/teuthology.yaml
    mode: 0755
  tags:
    - config

# Serve logs over HTTP
- include: setup_log_access.yml
  tags:
    - logs
