---
- name: Fail when on Ubuntu
  fail:
    msg: "pcp-webapi is only available when using upstream packages. Set upstream_repo to true."
  when: ansible_distribution == "Ubuntu" and upstream_repo|bool != true

- name: Install pcp-webapi
  yum:
    name: "{{ pcp_webapi_package }}"
    state: latest
  register: install_pcp_webapi
  when: ansible_pkg_mgr == "yum"

- name: Install pcp-webjs
  yum:
    name: "{{ pcp_webjs_package }}"
    state: latest
  register: install_pcp_webjs
  when: ansible_pkg_mgr == "yum"

- name: Install pcp-webapi
  apt:
    name: "{{ pcp_webapi_package }}"
    state: latest
  register: install_pcp_webapi
  when: ansible_pkg_mgr == "apt"

- name: Enable pmwebd
  service:
    name: "{{ pmwebd_service }}"
    enabled: yes
  register: enable_pmwebd

- name: Ship dashboard
  copy:
    src: "../files/{{ item }}"
    dest: "/usr/share/pcp/webapps/grafana/app/dashboards/"
    owner: root
    group: root
    mode: 0644
  with_items:
    - 1h1m.json
    - index.js
  tags:
    - dashboards

- name: Start pmwebd
  service:
    name: "{{ pmmgr_service }}"
    state: restarted
  when:
    install_pcp_webapi is changed or
    install_pcp_webjs is changed or
    enable_pmwebd is changed
