---
- name: Install cobbler
  apt:
    name: "{{ cobbler_package }}"
    state: latest
  register: install_cobbler

- name: Install extra cobbler packages
  apt:
    name: "{{ cobbler_extra_packages|list }}"
    state: latest
  when: cobbler_extra_packages|length > 0
