---
- name: Include secrets
  include_vars: "{{ item }}"
  no_log: true
  with_first_found:
    - "{{ secrets_path | mandatory }}/nameserver.yml"
    - empty.yml
  tags:
    - always

# Install and update system packages
- import_tasks: packages.yml
  tags:
    - packages

- name: Enable and start ntpd
  service:
    name: ntpd
    state: started
    enabled: yes
  tags:
    - always

# DDNS updates fail to create or edit jnl files without this
- name: Ensure permissions set for "{{ named_conf_zones_path }}"
  file:
    path: "{{ named_conf_zones_path }}"
    mode: '0700'
    state: directory
    owner: named
    group: named
  tags:
    - always

# Configure firewalld
- import_tasks: firewall.yml
  tags:
    - firewall

# Configure BIND
- import_tasks: config.yml
  tags:
    - config

# Compile and write zone files
- import_tasks: records.yml
  tags:
    - records
  when: (named_conf_slave is undefined) or
        (named_conf_slave is defined and named_conf_slave == false)
