---
- name: Increase the yum timeout.
  lineinfile:
    dest: /etc/yum.conf
    line: "timeout={{ yum_timeout }}"
    regexp: "^timeout="
    state: present

- name: Configure epel repos in /etc/yum.repos.d/
  template:
    src: yum_repo.j2
    dest: /etc/yum.repos.d/{{ item.key }}.repo
    owner: root
    group: root
    mode: 0644
  register: epel_repo
  with_dict: "{{ epel_repos }}"

- name: Configure local epel mirrorlists
  template:
    src: '{{ item }}'
    dest: '/etc/yum.repos.d/{{ item }}'
    owner: root
    group: root
    mode: 0644
  with_items:
    - epel-mirrorlist
    - epel-testing-mirrorlist

# A few times a year, we'd see a bunch of 404 errors during yum transactions that involved epel mirrors.
# It has to do with upstream EPEL being updated and mirrors lagging behind.
- name: Temporarily comment mirrorlist so we can update yum cache
  replace:
    path: "/etc/yum.repos.d/{{ item.key }}.repo"
    regexp: '^(.*mirror.*)'
    replace: '#\1'
  with_dict: "{{ epel_repos }}"

- name: Update yum cache
  shell: rm -rf /var/cache/yum/*; yum clean all; yum makecache

- name: Uncomment mirrorlist
  replace:
    path: "/etc/yum.repos.d/{{ item.key }}.repo"
    regexp: '^#(.*mirror.*)'
    replace: '\1'
  with_dict: "{{ epel_repos }}"
