---
- name: nrpe - Install SELinux dependencies
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
    - libsemanage-python
    - policycoreutils-python

# ignore_errors in case we don't have any repos
- name: nrpe - Ensure SELinux policy is up to date
  yum:
    name: selinux-policy-targeted
    state: latest
  ignore_errors: true

- name: nrpe - Set SELinux boolean nagios_run_sudo true
  seboolean:
    name: nagios_run_sudo
    state: yes
    persistent: yes

- name: nrpe - Remove SELinux policy package
  command: semodule -r nrpe
  failed_when: false

- name: nrpe - Copy SELinux type enforcement file
  copy:
    src: nagios/nrpe.te
    dest: /tmp/nrpe.te

- name: nrpe - Compile SELinux module file
  command: checkmodule -M -m -o /tmp/nrpe.mod /tmp/nrpe.te

- name: nrpe - Build SELinux policy package
  command: semodule_package -o /tmp/nrpe.pp -m /tmp/nrpe.mod

- name: nrpe - Load SELinux policy package
  command: semodule -i /tmp/nrpe.pp

- name: nrpe - Remove temporary files
  file:
    path: /tmp/nrpe.*
    state: absent
