---
- name: Configure common additional repos in /etc/yum.repos.d/
  template:
    src: yum_repo.j2
    dest: /etc/yum.repos.d/{{ item.key }}.repo
    owner: root
    group: root
    mode: 0644
  register: repo_file
  with_dict: "{{ common_yum_repos }}"
  when: common_yum_repos.keys() | length > 0

- name: Configure version specific repos in /etc/yum.repos.d/
  template:
    src: yum_repo.j2
    dest: /etc/yum.repos.d/{{ item.key }}.repo
    owner: root
    group: root
    mode: 0644
  register: version_repo_file
  with_dict: "{{ yum_repos }}"
  when: yum_repos.keys() | length > 0

- import_tasks: gpg_keys.yml
  when: ansible_distribution == "Fedora"
  tags:
    - gpg-keys

- name: Clean yum cache
  shell: yum clean all
  when: (repo_file is defined and repo_file is changed) or
        (gpg_keys is defined and gpg_keys is changed) or
        (version_repo_file is defined and version_repo_file is changed)
