---
# In non-Stream CentOS versions, ceph-cm-ansible takes care of overwriting the Distro/ISO-provided repo files.
# Since we convert from CentOS 8.X to CentOS Stream, we have to delete the Stream repo files that the process creates.
# We just don't want to rely on CentOS' infra to provide our mirror lists.  It has bitten us in the past.
- name: Clean up Stream distro-provided repos
  shell: "rm -rvf /etc/yum.repos.d/*Stream*"
  when:
    - ansible_lsb.description is defined
    - '"Stream" in ansible_lsb.description'

- set_fact:
    dash_stream: "-stream"
  when:
    - ansible_lsb.description is defined
    - '"Stream" in ansible_lsb.description'

- name: Configure local mirrorlists
  template:
    src: 'mirrorlists/{{ ansible_distribution_major_version }}/{{ item }}'
    dest: '/etc/yum.repos.d/{{ item }}'
    owner: root
    group: root
    mode: 0644
  with_items: "{{ yum_mirrorlists }}"
  when: yum_mirrorlists is defined

- name: Configure common additional repos in /etc/yum.repos.d/
  template:
    src: yum_repo.j2
    dest: /etc/yum.repos.d/{{ item.key }}.repo
    owner: root
    group: root
    mode: 0644
  register: repo_file
  with_dict: "{{ common_yum_repos }}"
  when: common_yum_repos.keys() | length > 0

- name: Configure version specific repos in /etc/yum.repos.d/
  template:
    src: yum_repo.j2
    dest: /etc/yum.repos.d/{{ item.key }}.repo
    owner: root
    group: root
    mode: 0644
  register: version_repo_file
  with_dict: "{{ yum_repos|default({}) | combine(additional_yum_repos|default({}), recursive=True) }}"
  when: (yum_repos.keys() | length > 0) or (additional_yum_repos.keys() | length > 0)

- name: Enable copr repos
  command: "dnf -y copr enable {{ item }}"
  with_items: "{{ copr_repos }}"
  when:
    - (ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 8)
    - copr_repos|length > 0

- import_tasks: gpg_keys.yml
  when: ansible_distribution == "Fedora"
  tags:
    - gpg-keys

- name: Clean yum cache
  shell: yum clean all
  when: (repo_file is defined and repo_file is changed) or
        (gpg_keys is defined and gpg_keys is changed) or
        (version_repo_file is defined and version_repo_file is changed)
