---
# vars specific to any rhel 8.x version

common_yum_repos:
  lab-extras:
    name: "lab-extras"
    baseurl: "http://{{ mirror_host }}/lab-extras/8/"
    enabled: 1
    gpgcheck: 0

packages:
  - '@core'
  - '@base'
  # for package-cleanup
  - dnf-utils
  - sysstat
  - libedit
  - boost-thread
  - xfsprogs
  - gdisk
  - parted
  - libgcrypt
  - fuse-libs
  - openssl
  - libuuid
  - podman
  - attr
  - ant
  - lsof
  - gettext
  - bc
  - xfsdump
  - blktrace
  - usbredir
  - libev-devel
  # for xfstests
  - ncurses-devel
  # for s3 tests

epel_packages: []

nfs_service: nfs-server

ntp_service_name: chronyd
