---
- name: Ensure ceph packages are not present.
  zypper:
    name: "{{ ceph_packages_to_remove|list }}"
    state: absent
  tags:
    - remove-ceph

- name: Ensure ceph dependency packages are not present.
  zypper:
    name: "{{ ceph_dependency_packages_to_remove|list }}"
    state: absent
  tags:
    - remove-ceph-dependency

- name: Remove packages
  zypper:
    name: "{{ packages_to_remove|list }}"
    state: absent
  when: packages_to_remove|length > 0

- name: Install packages
  zypper:
    name: "{{ packages|list }}"
    state: present
  when: packages|length > 0

- name: Upgrade packages
  zypper:
    name: "{{ packages_to_upgrade|list }}"
    state: latest
  when: packages_to_upgrade|length > 0
